### ISSUE TITLE
Memory efficiency

### ISSUE THREAD

**Issue by liaoyuhua** [DACUS1995/pytorch-mmap-dataset#4]
https://github.com/DACUS1995/pytorch-mmap-dataset/blob/7c1662bee5d03b4231b7073eecf79c04410836be/pytorch_mmap_dataset/dataset.py#L71

Hi, thanks for your good project. I am confused that if we have enough memory to load all input and label, why should we use mmap later?

**Comment by DACUS1995** [comment]
Hi @liaoyuhua, sorry for the late reply, you ask a good question here, for that case when we don't know the size and we need to iterate over the dataset to find it I shouldn't really keep the data in memory, just count it, I'll add this change asap.

Generally, if you can store everything in memory there should be little need to use mmap explicitly, the only thing that comes to mind is for cases when you use a python list (instead of something with contiguous memory representation) you might have bad performance due to the object access redirections.

Thank you!
